//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCD.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public System.DateTime created_utc_datetime { get; set; }
        public int created_by { get; set; }
        public System.DateTime modified_utc_datetime { get; set; }
        public int modified_by { get; set; }
        public bool delete_ind { get; set; }
        public bool active_ind { get; set; }
        public string CIK { get; set; }
        public Nullable<int> SIC { get; set; }
        public bool outsourced_ind { get; set; }
        public Nullable<int> incorp_country_id { get; set; }
        public string website { get; set; }
        public Nullable<int> company_status_id { get; set; }
        public Nullable<System.DateTime> effective_datetime { get; set; }
        public string IRS { get; set; }
        public string marketcap { get; set; }
        public string other_info { get; set; }
        public string EDINET { get; set; }
        public string company_background { get; set; }
        public Nullable<int> marketcap_currency_id { get; set; }
        public Nullable<System.DateTime> marketcap_datetime { get; set; }
        public string revenue { get; set; }
        public Nullable<int> revenue_currency_id { get; set; }
        public Nullable<System.DateTime> revenue_datetime { get; set; }
        public string founding_year { get; set; }
    }
}
